"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
	type = "prompt"
	alignment = "left"
	newline = true
[[blocks.segments]]
	type = "path"
	style = "plain"
	foreground = "blue"
	template = "{{ if .Root }}<red><i>{{ .Path }}</i>{{ else }}{{ .Path }}{{ end }}"
[blocks.segments.properties]
	style = "full"
[[blocks.segments]]
	type = "git"
	style = "plain"
	foreground = "darkGray"
[blocks.segments.properties]
	branch_icon = ""

[[blocks]]
	type = "prompt"
	alignment = "right"
[[blocks.segments]]
	type = "executiontime"
	style = "plain"
	template = "{{ .FormattedMs }}"
[blocks.segments.properties]
	threshold = 1500

[[blocks]]
	type = "prompt"
	alignment = "left"
	newline = true
[[blocks.segments]]
	type = "text"
	style = "plain"
	foreground = "magenta"
	template = "❯"

[transient_prompt]
	foreground = "magenta"
	template = "❯ "

[secondary_prompt]
	foreground = "magenta"
	template = "❯❯ "
